### ISSUE TITLE
'gcloud' is not recognized as a command

### ISSUE THREAD

**Issue by TMGMike** [nexsolab/azure-devops-google-cloud-tools#67]
Hi guys, 

I've been using this tool to install the Google Cloud SDK on my agent machines in Azure Pipelines, and haven't noticed any issues until recently (although I took a break for a little while so there was no activity). 

Installing the SDK succeeds, but when trying to authenticate with GCP (to upload build artefacts to GCS), it fails to find the command. The log shows that it has added the script to the PATH variable, so it shouldn't be failing... Unless a recent upgrade to the windows agents has caused the machine to require a reboot or something?

This is how I'm installing the SDK: 
```yaml

- task: GoogleCloudSdkTool@1
  displayName: 'Install GCP SDK'
  inputs:
    versionSpec: '393.x' # '315.x'

```

This is how I'm then authenticating (to be used when uploading the artefacts):

```yaml

- task: CmdLine@2
  displayName: 'Authenticate GCP'
  inputs:
    script: 'gcloud auth activate-service-account $(serviceAccount) --key-file=$(GcpKeyFile.secureFilePath) --project=[...]'
```

'gcloud' is not recognized as an internal or external command, operable program or batch file.
##[error]Cmd.exe exited with code '1'.
Finishing: Authenticate GCP

Any ideas? Did I miss a big change during my break? 

Edit: I'm also noticing that no matter what version I specify in the `versionSpec` attribute, it always seems to install 392... `Downloading: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-392.0.0-windows-x86_64.zip` - is this normal?
