### ISSUE TITLE
Delete operation should not error on record not found

### ISSUE THREAD

**Issue by DDavidsonOS** [nexsolab/azure-devops-google-cloud-tools#68]
We have been using the Delete operation as part of a cleanup pipeline we have:

```
- task: GoogleCloudDNS@0
    retryCountOnTaskFailure: 1
    displayName: GoogleCloudDNS Delete Record
    continueOnError: true
    inputs:
      authenticationMethod: 'jsonFile'
      jsonCredentials: '<CredFile>'
      operation: 'delete'
      recordZone: ${{ replace(parameters.zone, '.', '') }}
      recordName: ${{ parameters.cloudsitename }}.${{ parameters.zone }}
```

Based on how this runs in our development pipelines, sometimes things fail before creation of DNS records for the test environment. We iterate, and do environment clean up with the environment in an incomplete state.

So, the cleanup step will run as part of our environment cleanup pipeline and trigger the GoogleCloudDNS task, which will error because the zone record is not present, causing an error state in the pipeline.

The purpose of the delete operation is to enforce the lack of records. If those things do not exist I would assert that it would be a warning or verbose message, rather than an error state. The desired state is already present, so no work is done but it shouldn't error.

We are using continueOnError to work around this, but that means that if we had a different more important error - like credentials expired - it would still continue. 

There might be a good reason for the current design that I'm not seeing, though, since I'm new to Google DNS so I wanted to inquire as to whether this would be a good change, or is working as designed for good reason.
